# Generated by Django 5.2.7 on 2025-12-19 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_visitor', '0002_alter_visitor_options_alter_visitorlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-last_visit']},
        ),
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['-visited_at']},
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='created_at',
            new_name='first_visit',
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='timestamp',
            new_name='visited_at',
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='page_visited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='session_key',
            field=models.CharField(default='unkown', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='visit_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='track_visitor.visitor'),
        ),
        migrations.AlterModelTable(
            name='visitor',
            table='visitors',
        ),
        migrations.AlterModelTable(
            name='visitorlog',
            table='visitor_logs',
        ),
    ]
