# Generated by Django 5.2.7 on 2025-12-18 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('visit_count', models.IntegerField(default=1)),
                ('page_visited', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'visitors',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.CharField(max_length=255)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='track_visitor.visitor')),
            ],
            options={
                'db_table': 'visitor_logs',
                'ordering': ['-visited_at'],
            },
        ),
    ]
