# Generated by Django 5.2.7 on 2025-12-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visitorlog',
            options={},
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='first_visit',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='visited_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='page_visited',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visit_count',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(default='unkown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='referrer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_visitor.visitor'),
        ),
        migrations.AlterModelTable(
            name='visitor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='visitorlog',
            table=None,
        ),
    ]
