name: Run Django Tests


on:
  push:
    branches:
      - "main"        
  pull_request:
    branches:
      - "main"        

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd system
          python -m pip install --upgrade pip
          pip install -r backend/requirement.txt

      - name: Run Django Tests
        run: |
          cd system
          python manage.py test -- --watchAll=false
        env:
          DJANGO_SETTINGS_MODULE: config.settings

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install React dependencies
        run: |
          npm install

      - name: Run React Tests
        run: |
          npm test -- --watchAll=false