# Generated by Django 5.2.7 on 2025-12-19 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_visitor', '0003_alter_visitor_options_alter_visitorlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-last_visit'], 'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Visitor Log', 'verbose_name_plural': 'Visitor Logs'},
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='page',
            new_name='page_visited',
        ),
        migrations.RenameField(
            model_name='visitorlog',
            old_name='visited_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='page_visited',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='referrer',
        ),
        migrations.AddField(
            model_name='visitor',
            name='ip',
            field=models.GenericIPAddressField(default='unknown', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='referer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='visitor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='visitorlog',
            table=None,
        ),
    ]
